import mongoose from "mongoose";

const supplierReportDetailByPeriodSchema = new mongoose.Schema({
    "realizationreport_id": Number,
    "date_from": Date,
    "date_to": Date,
    "create_dt": Date,
    "rrd_id": Number,
    "gi_id": Number,
    "subject_name": String,
    "nm_id": Number,
    "brand_name": String,
    "sa_name": String,
    "ts_name": String,
    "barcode": String,
    "doc_type_name": String,
    "quantity": Number,
    "retail_price": Number,
    "retail_amount": Number,
    "sale_percent": Number,
    "commission_percent": Number,
    "office_name": String,
    "supplier_oper_name": String,
    "order_dt": Date,
    "sale_dt": Date,
    "rr_dt": Date,
    "shk_id": Number,
    "retail_price_withdisc_rub": Number,
    "delivery_amount": Number,
    "return_amount": Number,
    "delivery_rub": Number,
    "gi_box_type_name": String,
    "product_discount_for_report": Number,
    "supplier_promo": Number,
    "rid": Number,
    "ppvz_spp_prc": Number,
    "ppvz_kvw_prc_base": Number,
    "ppvz_kvw_prc": Number,
    "sup_rating_prc_up": Number,
    "is_kgvp_v2": Number,
    "ppvz_sales_commission": Number,
    "ppvz_for_pay": Number,
    "ppvz_reward": Number,
    "acquiring_fee": Number,
    "acquiring_bank": String,
    "ppvz_vw": Number,
    "ppvz_vw_nds": Number,
    "ppvz_office_id": Number,
    "ppvz_office_name": String,
    "ppvz_supplier_id": Number,
    "ppvz_supplier_name": String,
    "ppvz_inn": String,
    "declaration_number": String,
    "bonus_type_name": String,
    "sticker_id": String,
    "site_country": String,
    "penalty": Number,
    "additional_payment": Number,
    "rebill_logistic_cost": Number,
    "rebill_logistic_org": String,
    "kiz": String,
    "srid": String
});

const SupplierReportDetailByPeriod = mongoose.model("ReportDetail", supplierReportDetailByPeriodSchema);

export default SupplierReportDetailByPeriod;
